// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WinterFood.Data;

#nullable disable

namespace WinterFood.Migrations
{
    [DbContext(typeof(RecipeDbContext))]
    [Migration("20230219164258_Initial-Commit")]
    partial class InitialCommit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("WinterFood.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Amount")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Units")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("Ingredient");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = "1 pound",
                            Name = "Spaghetti",
                            RecipeId = 1,
                            Units = "box"
                        },
                        new
                        {
                            Id = 2,
                            Amount = "1 pound",
                            Name = "Ground Beef",
                            RecipeId = 1,
                            Units = "package"
                        },
                        new
                        {
                            Id = 3,
                            Amount = "24 ounces",
                            Name = "Tomato Sauce",
                            RecipeId = 1,
                            Units = "can"
                        },
                        new
                        {
                            Id = 4,
                            Amount = "1",
                            Name = "Onion",
                            RecipeId = 1,
                            Units = ""
                        });
                });

            modelBuilder.Entity("WinterFood.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CookTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrepTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Servings")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CookTime = "30 minutes",
                            Description = "Classic spaghetti bolognese made with ground beef, tomatoes, and pasta.",
                            ImageUrl = "https://www.example.com/spaghetti-bolognese.jpg",
                            Instructions = "Brown the ground beef and onions in a large pot. Add the garlic and cook for a minute. Add the beans, tomato sauce, tomato paste, chili powder, cumin, oregano, salt, pepper, and water. Simmer for 30 minutes, stirring occasionally.",
                            Name = "Spaghetti Bolognese",
                            PrepTime = "10 minutes",
                            Servings = 4
                        });
                });

            modelBuilder.Entity("WinterFood.Models.Ingredient", b =>
                {
                    b.HasOne("WinterFood.Models.Recipe", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WinterFood.Models.Recipe", b =>
                {
                    b.Navigation("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
